[package]
name = "fast-distances"
version = "0.0.1"
description = "A rust library to provide distances for multidimensional arrays"
authors = ["Eugene Hauptmann"]
edition = "2021"

[dependencies]
approx = "0.5.1"
ndarray = "0.16.1"
num = "0.4.3"
num-traits = "0.2.19"
